// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: hydlwjvvjfaiyvjqucsg

class SupabaseConfig {
  static const String supabaseUrl = 'https://hydlwjvvjfaiyvjqucsg.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5ZGx3anZ2amZhaXl2anF1Y3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MzU4NTEsImV4cCI6MjA3ODMxMTg1MX0.LtnLLqKreeQfxG9AoFYKMhjANcFW5tXnvH2xeYhKYVM';
}
